require 'json'
require 'uglifier'
require 'nokogiri'

SOURCE_DIRECTORY = 'source/'

task :default => [:package]

task :package do
  # Read the manifest file
  manifest = JSON.parse(File.read("#{SOURCE_DIRECTORY}manifest.json"))

  # Remove the existing packaged zip
  sh "rm package-*.zip"

  # Copy the source directory to the build directory
  sh "cp -r #{SOURCE_DIRECTORY} build/"

  # Minify JS files
  Dir['build/*.js'].each do |f|
    content = Uglifier.compile(File.read(f))
    File.open(f, 'w') { |o| o.write(content) }
  end

  # Minify inline JS
  Dir['build/*.html'].each do |f|
    input = File.read(f)

    doc = Nokogiri::HTML(input)

    doc.css('script').each do |script|
      content = Uglifier.compile(script.content)
      script.content = content
    end

    File.open(f, 'w') { |o| o.write(doc.to_s) }
  end

  # Create the packaged zip file
  sh "zip -r package-#{manifest['version']}.zip build -x '*.DS_Store'"

  # Remove the build dir
  sh 'rm -Rf build/'
end